/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pn;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testCaseOne() {
        Library classUnderTest = new Library();
        int input = 121;
        assertTrue("isPalindrome should return 'true'", classUnderTest.isPalindrome(input));
    }

    @Test public void testCaseTwo() {
        Library classUnderTest = new Library();
        int input = -121;
        assertFalse("isPalindrome should return 'false'", classUnderTest.isPalindrome(input));
    }

    @Test public void testCaseThree() {
        Library classUnderTest = new Library();
        int input = 10;
        assertFalse("isPalindrome should return 'false'", classUnderTest.isPalindrome(input));
    }

}
