/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zc;

import org.junit.Test;
import static org.junit.Assert.*;

public class SolutionTest {
    @Test
    public void testCaseOne() {
        Solution classUnderTest = new Solution();
        String input = "PAYPALISHIRING";
        int numRows = 3;
        String expected = "PAHNAPLSIIGYIR";
        assertEquals(expected, classUnderTest.convert(input, numRows));
    }

    @Test
    public void testCaseTwo() {
        Solution classUnderTest = new Solution();
        String input = "PAYPALISHIRING";
        int numRows = 4;
        String expected = "PINALSIGYAHRPI";
        assertEquals(expected, classUnderTest.convert(input, numRows));
    }

    @Test
    public void testCaseThree() {
        Solution classUnderTest = new Solution();
        String input = "P";
        int numRows = 3;
        String expected = "P";
        assertEquals(expected, classUnderTest.convert(input, numRows));
    }

    @Test
    public void testCaseFour() {
        Solution classUnderTest = new Solution();
        String input = "";
        int numRows = 3;
        String expected = "";
        assertEquals(expected, classUnderTest.convert(input, numRows));
    }

    @Test
    public void testCaseFive() {
        Solution classUnderTest = new Solution();
        String input = "AB";
        int numRows = 1;
        String expected = "AB";
        assertEquals(expected, classUnderTest.convert(input, numRows));
    }

    @Test
    public void testCaseSix() {
        Solution classUnderTest = new Solution();
        String input = "ABC";
        int numRows = 2;
        String expected = "ACB";
        assertEquals(expected, classUnderTest.convert(input, numRows));
    }
}
