/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lps;

import org.junit.Test;
import static org.junit.Assert.*;

public class SolutionTest {
    @Test
    public void testCaseOne() {
        Solution classUnderTest = new Solution();
        String input = "babad";
        String expected = "bab";
        assertEquals(expected, classUnderTest.longestPalindrome(input));
    }

    @Test
    public void testCaseTwo() {
        Solution classUnderTest = new Solution();
        String input = "cbbd";
        String expected = "bb";
        assertEquals(expected, classUnderTest.longestPalindrome(input));
    }

    @Test
    public void testCaseThree() {
        Solution classUnderTest = new Solution();
        String input = "a";
        String expected = "a";
        assertEquals(expected, classUnderTest.longestPalindrome(input));
    }

    @Test
    public void testCaseFour() {
        Solution classUnderTest = new Solution();
        String input = "abcda";
        String expected = "a";
        assertEquals(expected, classUnderTest.longestPalindrome(input));
    }
}
