/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package twosum;

import org.junit.Test;
import static org.junit.Assert.*;

public class SolutionTest {
    @Test public void testShouldReturnFirstTwoIndices() {
        Solution classUnderTest = new Solution();
        int[] nums = {2, 7, 11, 15};
        int target = 9;
        int[] expected = {0, 1};
        assertArrayEquals("should return the first two indices", expected, classUnderTest.twoSum(nums, target));
    }
}
