/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package motsa;

import org.junit.Test;
import static org.junit.Assert.*;

public class SolutionTest {
    @Test
    public void testCaseOne() {
        Solution classUnderTest = new Solution();
        int[] nums1 = {1, 3};
        int[] nums2 = {2};
        double expected = 2.0;
        assertEquals(expected, classUnderTest.findMedianSortedArrays(nums1, nums2), 0.01);
    }

    @Test
    public void testCaseTwo() {
        Solution classUnderTest = new Solution();
        int[] nums1 = {1, 2};
        int[] nums2 = {3, 4};
        double expected = 2.5;
        assertEquals(expected, classUnderTest.findMedianSortedArrays(nums1, nums2), 0.01);
    }

    @Test
    public void testCaseThree() {
        Solution classUnderTest = new Solution();
        int[] nums1 = {1, 3};
        int[] nums2 = {5, 6};
        double expected = 4;
        assertEquals(expected, classUnderTest.findMedianSortedArrays(nums1, nums2), 0.01);
    }

    @Test
    public void testCaseFour() {
        Solution classUnderTest = new Solution();
        int[] nums1 = {1};
        int[] nums2 = {};
        double expected = 1;
        assertEquals(expected, classUnderTest.findMedianSortedArrays(nums1, nums2), 0.01);
    }
}
