/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sti;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testCaseOne() {
        Library classUnderTest = new Library();
        String input = "42";
        int expected = 42;
        assertEquals(expected, classUnderTest.myAtoi(input));
    }

    @Test public void testCaseTwo() {
        Library classUnderTest = new Library();
        String input = "   -42";
        int expected = -42;
        assertEquals(expected, classUnderTest.myAtoi(input));
    }

    @Test public void testCaseThree() {
        Library classUnderTest = new Library();
        String input = "4193 with words";
        int expected = 4193;
        assertEquals(expected, classUnderTest.myAtoi(input));
    }

    @Test public void testCaseFour() {
        Library classUnderTest = new Library();
        String input = "words and 987";
        int expected = 0;
        assertEquals(expected, classUnderTest.myAtoi(input));
    }

    @Test public void testCaseFive() {
        Library classUnderTest = new Library();
        String input = "-91283472332";
        int expected = -2147483648;
        assertEquals(expected, classUnderTest.myAtoi(input));
    }

    @Test public void testCaseSix() {
        Library classUnderTest = new Library();
        String input = "20000000000000000000";
        int expected = 2147483647;
        assertEquals(expected, classUnderTest.myAtoi(input));
    }

    @Test public void testCaseSeven() {
        Library classUnderTest = new Library();
        String input = "  0000000000012345678";
        int expected = 12345678;
        assertEquals(expected, classUnderTest.myAtoi(input));
    }
}
