/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lswrc;

import org.junit.Test;
import static org.junit.Assert.*;

public class SolutionTest {
    @Test public void testCaseOne() {
        Solution classUnderTest = new Solution();
        String input = "abcabcbb";
        int expected = 3;
        assertEquals("", expected, classUnderTest.lengthOfLongestSubstring(input));
    }

    @Test public void testCaseTwo() {
        Solution classUnderTest = new Solution();
        String input = "bbbbb";
        int expected = 1;
        assertEquals("", expected, classUnderTest.lengthOfLongestSubstring(input));
    }

    @Test public void testCaseThree() {
        Solution classUnderTest = new Solution();
        String input = "pwwkew";
        int expected = 3;
        assertEquals("", expected, classUnderTest.lengthOfLongestSubstring(input));
    }

    @Test public void testCaseFour() {
        Solution classUnderTest = new Solution();
        String input = "dvdf";
        int expected = 3;
        assertEquals("", expected, classUnderTest.lengthOfLongestSubstring(input));
    }
}
